config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'homes#index'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  resources :users, only: %i[destroy]
  namespace :users do
    root to: 'homes#index'
    resources :personal_words, only: %i[index destroy create]
    resources :daily_user_word_records, only: :index
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/daily_last_tweet_id_for_user.rb
# == Schema Information
#
# Table name: daily_last_tweet_id_for_users
#
#  id         :uuid             not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  tweet_id   :integer
#  user_id    :uuid             not null
#
# Indexes
#
#  index_daily_last_tweet_id_for_users_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class DailyLastTweetIdForUser < ApplicationRecord
end

app/models/daily_user_word_record.rb
# == Schema Information
#
# Table name: daily_user_word_records
#
#  id                   :uuid             not null, primary key
#  all_daily_word_count :integer
#  count                :integer          not null
#  created_on           :datetime
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  personal_word_id     :uuid             not null
#  user_id              :uuid             not null
#
# Indexes
#
#  index_daily_user_word_records_on_personal_word_id  (personal_word_id)
#  index_daily_user_word_records_on_user_id           (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (personal_word_id => personal_words.id)
#  fk_rails_...  (user_id => users.id)
#
class DailyUserWordRecord < ApplicationRecord
  belongs_to :user
  belongs_to :personal_word
end

app/models/negative_word.rb
# == Schema Information
#
# Table name: personal_words
#
#  id         :uuid             not null, primary key
#  content    :string           not null
#  type       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :uuid
#
# Indexes
#
#  index_personal_words_on_type     (type)
#  index_personal_words_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class NegativeWord < PersonalWord
end

app/models/personal_word.rb
# == Schema Information
#
# Table name: personal_words
#
#  id         :uuid             not null, primary key
#  content    :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :uuid
#
# Indexes
#
#  index_personal_words_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class PersonalWord < ApplicationRecord
  belongs_to :user
  validates :content, uniqueness: { scope: :user_id }
end

app/models/positive_word.rb
# == Schema Information
#
# Table name: personal_words
#
#  id         :uuid             not null, primary key
#  content    :string           not null
#  type       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :uuid
#
# Indexes
#
#  index_personal_words_on_type     (type)
#  index_personal_words_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class PositiveWord < PersonalWord
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :uuid             not null, primary key
#  icon_image :string
#  nickname   :string           not null
#  uid        :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class User < ApplicationRecord
  has_many :personal_words, dependent: :destroy
  has_many :positive_words, dependent: :destroy
  has_many :negative_words, dependent: :destroy
  has_many :daily_user_word_records, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @current_user = current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user_data = request.env['omniauth.auth']
    unless user_data
      flash[:alert] = 'twitterでのログインに失敗しました。'
      redirect_to root_url
    end

    user = User.find_by(uid: user_data[:uid])
    if user
      flash[:success] = "#{user.nickname}様ようこそ！"
      log_in(user) && redirect_to(users_root_path)
      return
    end

    new_user = User.new(
      uid: user_data[:uid],
      nickname: user_data[:info][:nickname]
    )
    if new_user.save
      log_in new_user
      flash[:success] = 'ユーザ登録しました'
      redirect_to users_root_path
    else
      flash[:alert] = 'ユーザ登録に失敗しました'
      redirect_to root_url
    end
  end

  def destroy
    if signed_in?
      log_out
      flash[:success] = 'ログアウトしました'
    end
    redirect_to root_url
  end
end

app/controllers/users/daily_user_word_records_controller.rb
class Users::DailyUserWordRecordsController < UsersController
  def index
    @current_user = current_user
    @daily_records = @current_user.daily_user_word_records
  end
end

app/controllers/users/homes_controller.rb
class Users::HomesController < UsersController
  def index
    @current_user = current_user
    @yesterday_word_records = @current_user.daily_user_word_records.includes(:personal_word).where(created_on: 1.day.ago.all_day)
    @positive_words = @current_user.positive_words.limit(5)
    @negative_words = @current_user.negative_words.limit(5)
  end
end

app/controllers/users/personal_words_controller.rb
class Users::PersonalWordsController < UsersController
  permits :content, :type

  def create(personal_word)
    p 'create!'
    p personal_word
    @words = current_user.personal_words
    word_class = personal_word['type'].camelize.constantize
    @personal_word = word_class.new(content: personal_word['content'], user_id: current_user.id)
    if @personal_word.save
      redirect_to users_personal_words_path
    else
      render :index
    end
  end

  def index
    @words = current_user.personal_words
    @personal_word = PersonalWord.new
  end

  def destroy(id)
    return unless current_user.personal_words.pluck(:id).include?(id)

    personal_word = PersonalWord.find_by(id: id)
    personal_word.destroy!
    redirect_to users_personal_words_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_login
  permits :id
  def destroy(id)
    return unless current_user.id == id
    if current_user.destroy
      flash.now[:info] = 'アカウントの削除が完了しました。ご利用ありがとうございました。'
    end
    redirect_to root_path
  end

  private

  def ensure_login
    redirect_to root_path unless current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete :user_id
    @current_user = nil
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def signed_in?
    !current_user.nil?
  end
end

app/views/application/_flash.html.haml
- if flash.any?
  .flash
    - flash.each do |type, message|
      = content_tag(:div, message, class: "#{type} m-2 mb-5")

app/views/homes/index.html.haml
%div{style: "display: flex;justify-content: center;width: 100vw;height: 60vh; align-items:center;"}
  %span.is-size-1.is-hidden-tablet
    outsinya
  %span.is-hidden-mobile{style: 'font-size: 5rem;'}
    outsinya

%div{style: 'font-size:12px; margin:10px 30px; text-align:center;'}
  言葉を登録することでSNSでの人との繋がりを考えるきっかけを作るお手伝いをする。
  %br
  アウトサイニャーはそのために生まれたサービスです。

-# 使い方
.mb-5{style: 'margin-left: 10vw;margin-right: 10vw; margin-bottom:15px;'}
  %div{style: 'margin-top: 30vh;'}
    %div
      .my-6.has-text-weight-bold.is-size-4
        アウトサイニャーのはじめ方
  .tile.is-ancestor
    .tile.is-parent
      %article.tile.is-child.box
        %p.subtitle.is-size-6 1. お持ちのTwitterアカウントを通じて会員登録しましょう
        .content.has-text-centered
          = image_tag 'step_1.png'
    .tile.is-parent
      %article.tile.is-child.box
        %p.subtitle.is-size-6 2. 「嬉しい言葉」と「苦手な言葉」をアウトサイニャーに教えてください。
        .content.has-text-centered.pt-4
          = image_tag 'step_2.png'
    .tile.is-parent
      %article.tile.is-child.box
        %p.subtitle.is-size-6 3. アウトサイニャーが毎日のあなたへのSNS上の言葉を可視化します
        .content.has-text-centered.pt-4
          = image_tag 'step_3.png'
- unless current_user
  = link_to '/auth/twitter', class: 'button is-medium has-text-white has-text-weight-bold has-text-centered mb-1',
    style: 'background: #1DA1F2; margin: 0 auto; display: flex; width: 300px; padding:15px;' do
    - url = asset_path('twitter.png')
    %span{style: "background: url(#{url}) no-repeat; background-size: 40px 40px; width: 40px; height:40px; margin-left: -10px;"}
    Twitterアカウントで登録
  = link_to '/auth/twitter', class: 'has-text-grey-dark button is-text has-text-centered is-small',
    style: 'margin: 0 auto; display: flex; width: 200px' do
    %p
      既に登録済みの方はこちらからログイン


-# よくある質問
.mb-6.pb-6{style: 'margin-left: 10vw;margin-right: 10vw; margin-bottom:15px;'}
  %div{style: 'margin-top: 10vh;'}
    %div
      .my-6.has-text-weight-bold.is-size-4
        よくある質問
  .mb-5
    .my-4.is-size-5.has-text-weight-bold
      このサービスは何ですか？
    .my-2.is-size-6
      会員登録したユーザの方が登録した「嬉しい言葉」「嫌な言葉」が、ユーザの方に向けてどのくらいTwitter上で発言されているかを数値として保存し、状態を可視化することのできるサービスです。
      %br
      昨今のSNS上で問題になっている「心ない言葉を発してしまう」が実際にどうなのかを少し客観的な視点から数値として見つめることで、視野を広げるきっかけになればと作成しました。
      %br
      利用規約は
      = link_to 'こちら', page_path('terms'), target: '_blank'
      プライバシーポリシーは
      = link_to 'こちら', page_path('privacy'), target: '_blank'
      です。
  .mb-5
    .my-4.is-size-5.has-text-weight-bold
      Twitter認証を使用した会員登録とはなんですか？
    .my-2.is-size-6
      本サービスではサービスを利用する皆さんのメールアドレスもパスワードも保存しません。
      %br
      その変わりに、サービス利用者の方にTwitterのログイン情報をご入力いただき、認証することでサービスをご利用いただけるようになります。
      %br
      その際、サービス利用者のTwitterのログイン情報をサービスが取得し保存することはございませんのでご安心してご利用ください。
  .mb-5
    .my-4.is-size-5.has-text-weight-bold
      Twitter認証でアプリ連携するときに表示される「このアプリケーションは次のことができます」の用途を教えてください。
    .my-2.is-size-6
      %ul.mb-6
        %li.mb-4
          %blockquote.mb-3
            ・このアカウントのタイムラインに表示されるツイート（非公開ツイートを含む）や、リストとコレクションを確認する。
          .ml-2
            本サービスではこの機能は利用しません。
            タイムラインのツイートを取得することはなく、検索結果に表示される結果を取得しています。
            %br
            何度ユーザあてに発行されたツイートのうち、ご登録いただいた「好きな言葉」「嫌いな言葉」が含まれているかカウントを行い"回数"を保存しますが、
            取得したツイート自体を本サービスが保存するということはございませんので、ご安心ください。
        %li.mb-4
          %blockquote.mb-3
            ・このアカウントでプロフィール情報とアカウントの設定を確認する。
          .ml-2
            本サービスにログインしている時のユーザ名の表示に使用します。
            %br
            また、Twitter上での投稿のうち、ユーザ名あての書き込み内容の取得のために使用します。
        %li.mb-4
          %blockquote.mb-3
            ・フォロー、ミュート、ブロックしているアカウントを確認する。
          .ml-2
            本サービスではこの機能は利用しません。
      %div
        アプリ連携の画面で記載されていないことは、アプリ連携されていたとしてもデータの取得や操作を本サービスが行うことは出来ません。
        %br
        ダイレクトメッセージの閲覧や送信も、この本サービスご利用時に必要になる上記の権限では利用出来ません。
        %br
        サービスご利用にあたり、Twitterのアプリ連携に関しては上記内容をご確認のうえ、ご利用ください。
  .mb-5
    .my-4.is-size-5.has-text-weight-bold
      サービスを利用するのは無料ですか？
    .my-2.is-size-6
      はい。
      %br
      無料でご利用いただけます。
      %br
      ただし、サイトを閲覧するためのネット接続環境はサービス利用者の方にご用意いただく必要がございます。

.has-text-centered
  = image_tag 'before_home_footer.png'

app/views/layouts/_error_message.html.haml
- if model.errors.any?
  .alert
    %ul
      - model.errors.full_messages.each do |message|
        %li= message

app/views/layouts/_footer.html.haml
.footer_wrap.has-text-white{style: 'background: #000; text-align: center; bottom: 0; width: 100%; padding: 10px 5px;'}
  %div
    %span
      = link_to '利用規約', page_path('terms'), class: 'has-text-white is-size-7'
    %span
      |
    %span
      = link_to 'プライバシーポリシー', page_path('privacy'), class: 'has-text-white is-size-7'
    %span
      = link_to '公式Twitterアカウント', 'https://twitter.com/out_sinya',
        class: 'has-text-white is-size-7', target: '_blank'
    - if current_user
      %span
        |
      = link_to '退会はこちら', user_path(current_user.id), method: :delete, class: 'is-size-7 has-text-white', data: { confirm: '本当にアカウントを削除して大丈夫ですか？' }
  © 2020 outsinya All rights reserved

app/views/layouts/_header.html.haml
- is_static_page = %w[/privacy /terms].include?(request.path)
%nav.navbar.is-fixed-top{"aria-label" => "main navigation", :role => "navigation", style: 'border-bottom: #eded 1px solid; justify-content: space-between; display: flex;align-items: center;'}
  .navbar-brand
    = link_to root_path, class: 'navbar-item' do
      = image_tag 'outsinya_site_logo.png', width: "80", height: "80", style:'max-height: initial'
  - unless is_static_page
    #navbarBasicExample.navbar-menu
      .navbar-end
        .navbar-item
          - if @current_user.present?
            .buttons
              = link_to 'ログアウト', logout_path, class: 'button is-light has-text-weight-bold'
              = link_to '単語の追加', users_personal_words_path, class: 'button is-brand_primary_color has-text-white has-text-weight-bold',style: 'border: none;'
          - else
            .buttons
              = link_to 'ログイン', '/auth/twitter', class: 'button is-light has-text-weight-bold'
              = link_to '新規登録', '/auth/twitter', class: 'button is-brand_primary_color has-text-white has-text-weight-bold', style: 'border:none;'
    .is-hidden-tablet.mr-3
      - if @current_user.present?
        = link_to '単語の追加', users_personal_words_path, class: 'button is-brand_primary_color has-text-white has-text-weight-bold is-small', style: 'border:none;'
      - else
        = link_to '新規登録', '/auth/twitter', class: 'button is-brand_primary_color has-text-white has-text-weight-bold is-small', style: 'border:none;'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Outsinya</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name='viewport' content="width=device-width, initial-scale=1">
    <meta name="description" content="言葉を登録することでSNSでの人との繋がりを考えるきっかけを作るお手伝いをする。アウトサイニャーはそのために生まれたサービスです。">
    <meta charset="utf-8">
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag('favicon.ico') %>
    <meta name="google-site-verification" content="_NpRmBEas6zW6NUfY23UeJYt3fT5aOuxpga5WjLafuY" />
  </head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-177201807-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-177201807-1');
  </script>


  <body style="margin: 0;display: flex;flex-flow: column;min-height: 100vh;border:none;">
    <%= render 'layouts/header' %>
    <div class="main" style="flex: 1; padding-top: 100px;">
      <%= render 'flash' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/privacy.html.haml
%div{style: 'margin: auto 20px;'}
  .is-size-4.has-text-weight-bold.mb-3
    プライバシーポリシー
  %p
    運営者は、本ウェブサイト上で提供するサービス（以下,「本サービス」といいます。）における，ユーザーの個人情報の取扱いについて，以下のとおりプライバシーポリシー（以下，「本ポリシー」といいます。）を定めます。
  %p{style: 'margin-bottom: 20px;'}
    万一ご同意いただけない場合には、大変申し訳ありませんが、ご利用をお控えください。ご利用いただいた場合には、下記の諸条件すべてに同意いただいたものとさせていただきます。
  .is-size-5.has-text-weight-bold.mb-3
    第1条（個人情報の収集方法）
  %div{style: 'margin-bottom: 20px;'}
    本サービスでは、サービスのご提供のため、Twitterのアプリケーション認証時に以下の情報を取得・記録しています。
    %div
      ・ユーザー名
  .is-size-5.has-text-weight-bold.mb-3
    第2条（個人情報を収集・利用する目的）
  %p{style: 'margin-bottom: 20px;'}
    本サービスが個人情報を収集・利用する目的は，以下のとおりです。
  %ul{style: 'list-style:none; margin-bottom: 20px;'}
    %li
      1. 本サービスの提供・運営のため
    %li
      2. ユーザーからのお問い合わせに回答するため（本人確認を行うことを含む）
    %li
  .is-size-5.has-text-weight-bold.mb-3
    第3条（個人情報の削除について)
  %p{style: 'margin-bottom: 20px;'}
    本サービスに保存されている情報は、利用者様ご本人の希望により削除することが出来ます。
    %br
    その場合は、利用者様ご本人様からのお届け出であることが確認された後、ご対応をいたします。
  .is-size-5.has-text-weight-bold.mb-3
    第4条（個人情報の第三者提供）
  %p
    本サービスでは、原則として以下の場合を除き、利用者様の個人情報を第三者に提供することはありません。
  %ul{style: 'margin-bottom: 20px;'}
    %li
      1. 利用者様ご本人の同意に基づく場合。
    %li
      2. 裁判所や警察等の公的機関から法律に基づく正式な照会を受けて開示が請求され、これに応じる場合。
  .is-size-5.has-text-weight-bold.mb-3
    第5条（プライバシーポリシーの変更）
  %ul{style: 'margin-bottom: 20px;'}
    %li
      1. 本ポリシーの内容は，法令その他本ポリシーに別段の定めのある事項を除いて，ユーザーに通知することなく，変更することができるものとします。
    %li
      2. 本サービスが別途定める場合を除いて，変更後のプライバシーポリシーは，本ウェブサイトに掲載したときから効力を生じるものとします。

app/views/pages/terms.html.haml
%div{style: 'margin: auto 20px;'}
  .is-size-4.has-text-weight-bold.mb-3
    利用規約
  %p
    この利用規約（以下，「本規約」といいます。）は，このウェブサイトの運営者（以下，「運営者」といいます。）が提供するサービス「Outsinya」（以下，「本サービス」といいます。）の利用条件を定めるものです。登録ユーザーの皆さま（以下，「ユーザー」といいます。）には，本規約に従って，本サービスをご利用いただきます。
  %p{style: 'margin-bottom: 20px;'}
    万一ご同意いただけない場合には、大変申し訳ありませんが、ご利用をお控えください。ご利用いただいた場合には、下記の諸条件すべてに同意いただいたものとさせていただきます。
  .is-size-5.has-text-weight-bold.mb-3
    第1条（適用）
  %p{style: 'margin-bottom: 20px;'} 本規約は，ユーザーと運営者との間の本サービスの利用に関わる一切の関係に適用されるものとします。
  .is-size-5.has-text-weight-bold.mb-3
    第2条（利用登録）
  %ul{style: 'list-style: none; margin-bottom: 20px;'}
    %li
      1. ユーザーは，本サービスが定めるウェブサービスのアカウント認証により，利用登録を完了することができます。
    %li
      2. 本サービスは、無料で登録・ご利用いただけるものとします。但しアクセスにかかる通信費用は利用者様の負担となります。

  .is-size-5.has-text-weight-bold.mb-3
    第3条（禁止事項）
  %p{style: 'margin-bottom: 20px;'}
    ユーザーは，本サービスの利用にあたり，以下の行為をしてはなりません。
  %ul{style: 'list-style:none; margin-bottom: 20px;'}
    %li
      1. 法令または公序良俗に違反する行為
    %li
      2. 犯罪行為に関連する行為
    %li
      3. 本サービスの内容等，本サービスに含まれる著作権を侵害する行為
    %li
      4. 本サービスのサーバー、またはネットワークの機能を破壊したり，妨害したりする行為
    %li
      5. 本サービスによって得られた情報を商業的に利用する行為
    %li
      6. 本サービスの運営を妨害するおそれのある行為
    %li
      7. 不正アクセスをし，またはこれを試みる行為
    %li
      8. 他のユーザーに関する個人情報等を収集または蓄積する行為
    %li
      9. 不正な目的を持って当サービスを利用する行為
    %li
      10. 本サービスの他のユーザーまたはその他の第三者に不利益，損害，不快感を与える行為
    %li
      11. 他のユーザーに成りすます行為
    %li
      12. 面識のない異性との出会いを目的とした行為
    %li
      13. 本サービスに関連して，反社会的勢力に対して直接または間接に利益を供与する行為
    %li
      14. その他，運営者が不適切と判断する行為
  .is-size-5.has-text-weight-bold.mb-3
    第4条（本サービスの提供の停止等）
  %ul{style: 'margin-bottom: 20px;'}
    %li
      1. 運営者は，以下のいずれかの事由があると判断した場合，ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。
      %ul{style: 'list-style:none;'}
        %li
          1. 本サービスにかかるコンピュータシステムの保守点検または更新を行う場合
        %li
          2. 地震，落雷，火災，停電または天災などの不可抗力により，本サービスの提供が困難となった場合
        %li
          3. コンピュータまたは通信回線等が事故により停止した場合
        %li
          4. その他，運営者が本サービスの提供が困難と判断した場合
    %li
      2. 運営者は，本サービスの提供の停止または中断により，ユーザーまたは第三者が被ったいかなる不利益または損害についても，一切の責任を負わないものとします。
  .is-size-5.has-text-weight-bold.mb-3
    第5条（利用制限および登録抹消）
  %ul{style: 'list-style:none; margin-bottom: 20px;'}
    %li
      1. 本サービスは，ユーザーが以下のいずれかに該当する場合には，事前の通知なく，ユーザーに対して，本サービスの全部もしくは一部の利用を制限し，またはユーザーとしての登録を抹消することができるものとします。
      %ul{style: 'list-style:none;'}
        %li
          1. 本規約のいずれかの条項に違反した場合
        %li
          2. その他，本サービスの利用を適当でないと判断した場合
    %li
      2. 本サービスは，本条に基づき本サービスが行った行為によりユーザーに生じた損害について，一切の責任を負いません。
  .is-size-5.has-text-weight-bold.mb-3
    第6条（退会）
  %p{style: 'margin-bottom: 20px;'} ユーザーは，本サービスの定める退会手続により，本サービスから退会できるものとします。その際、本サービスに保存されたユーザに関連する全てのデータは削除いたします。
  .is-size-5.has-text-weight-bold.mb-3
    第7条（保証の否認および免責事項）
  %ul{style: 'list-style:none; margin-bottom: 20px;'}
    %li
      1. 運営者は，本サービスに事実上または法律上の瑕疵（安全性，信頼性，正確性，完全性，有効性，特定の目的への適合性，セキュリティなどに関する欠陥，エラーやバグ，権利侵害などを含みます。）がないことを明示的にも黙示的にも保証しておりません。
    %li
      2. 運営者は，本サービスに起因してユーザーに生じたあらゆる損害について一切の責任を負いません。
    %li
      3. 運営者は，本サービスのサーバに保存されたユーザー情報や投稿内容が何らかの理由で毀損・滅失した場合において一切の責任を負いません。
    %li
      4. 運営者は，本サービスに関して，ユーザーと他のユーザーまたは第三者との間において生じた取引，連絡または紛争等について一切責任を負いません。
  .is-size-5.has-text-weight-bold.mb-3
    第8条（サービス内容の変更等）
  %p{style: 'margin-bottom: 20px;'} 運営者は，ユーザーに通知することなく，本サービスの内容を変更しまたは本サービスの提供を中止することができるものとし，これによってユーザーに生じた損害について一切の責任を負いません。
  .is-size-5.has-text-weight-bold.mb-3
    第9条（利用規約の変更）
  %p{style: 'margin-bottom: 20px;'} 本サービスは，必要と判断した場合には，ユーザーに通知することなくいつでも本規約を変更することができるものとします。なお，本規約の変更後，本サービスの利用を開始した場合には，当該ユーザーは変更後の規約に同意したものとみなします。
  .is-size-5.has-text-weight-bold.mb-3
    第10条（個人情報の取扱い）
  %p{style: 'margin-bottom: 20px;'} 本サービスは，本サービスの利用によって取得する個人情報については，「プライバシーポリシー」に従い適切に取り扱うものとします。
  .is-size-5.has-text-weight-bold.mb-3
    第11条（準拠法・裁判管轄）
  %ul{style:'list-style:none; margin-bottom: 20px;'}
    %li
      1. 本規約の解釈にあたっては，日本法を準拠法とします。
    %li
      2. 本サービスに関して紛争が生じた場合には，東京地方裁判所を専属管轄裁判所とします。
  %p 以上

app/views/users/daily_user_word_records/index.html.haml
- @daily_records.each do |record|
  = record.word
  = record.count
  = "(#{record.created_on})"
  %br